language: java
jdk:
  - oraclejdk8
sudo: true
services:
 - docker
 - mongodb
install: true
before_install:
 - docker-compose up --build -d event-store
 - bash ./wait-for-it.sh "event-store:2113" -- echo "event-store 2113 is up"
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - sudo apt-get install jq
 - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
script:
 - mvn clean install
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
 - docker-compose down
cache:
  directories:
    - $HOME/.m2
