language: java
jdk:
  - oraclejdk8
sudo: true
services:
 - docker
 - mongodb
install: true
before_install:
 - docker-compose up --build -d event-store
 - bash run-travis.sh
script:
 - mvn clean install
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - docker-compose down
cache:
  directories:
    - $HOME/.m2