language: java
jdk:
  - oraclejdk8
sudo: true
services:
 - docker
 - mongodb
install: true
before_install:
 - docker-compose up --build -d event-store
 - bash ./wait-for-it.sh "event-store:2113" -- echo "event-store 2113 is up"
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
 - mvn clean install
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - docker-compose down
cache:
  directories:
    - $HOME/.m2