version: '2'
services:
 setup:
  image: maven:3.5.0-jdk-8
  volumes:
   - .:/home/application
  command: ["/home/application/run.sh"]
  depends_on:
    - event-store
 mongodb:
   image: mongo:latest
   container_name: "mongodb"
   ports:
    - 27017:27017
 event-store:
   image: eventstore/eventstore
   ports:
     - "2113:2113"
     - "1113:1113"
   extra_hosts:
     - "eventstore.com:127.0.0.1"
     - "localhost:127.0.0.1"
   restart: always
