version: '2'
services:
 setup:
  image: maven:3.5.0-jdk-8
  volumes:
   - .:/home/application
  command: ["/home/application/run.sh"]
  depends_on:
    - event-store
 mongodb:
   image: mongo:latest
   container_name: "mongodb"
   ports:
    - 27017:27017
 event-store:
   image: eventstore/eventstore
   ports:
     - "2113:2113"
     - "1113:1113"
   extra_hosts:
     - "eventstore.com:127.0.0.1"
     - "localhost:127.0.0.1"
   restart: always
 vitta-challenge-command-application-1:
   image: zacacj/vitta-challenge-command-application:1.0-SNAPSHOT
   depends_on:
     - setup
   restart: always
 vitta-challenge-command-application-2:
   image: zacacj/vitta-challenge-command-application:1.0-SNAPSHOT
   depends_on:
     - setup
   restart: always
 vitta-challenge-query-application-1:
   image: zacacj/vitta-challenge-query-application:1.0-SNAPSHOT
   depends_on:
     - setup
   restart: always
 vitta-challenge-query-application-2:
    image: zacacj/vitta-challenge-query-application:1.0-SNAPSHOT
    depends_on:
      - setup
    restart: always
 vitta-challenge-ui-application-1:
    image: zacacj/vitta-challenge-ui-application:1.0-SNAPSHOT
    depends_on:
      - setup
    restart: always
 vitta-challenge-ui-application-2:
    image: zacacj/vitta-challenge-ui-application:1.0-SNAPSHOT
    depends_on:
      - setup
    restart: always
 proxy:
   build: ./nginx
   ports:
    - 8888:8888
    - 8889:8889
    - 8890:8890
   depends_on:
     - vitta-challenge-command-application-1
     - vitta-challenge-command-application-2
     - vitta-challenge-query-application-1
     - vitta-challenge-query-application-2
     - vitta-challenge-ui-application-1
     - vitta-challenge-ui-application-2
   restart: always
