version: '2'
services:
 proxy:
   build: ./nginx
   ports:
    - 8888:8888
   restart: always
 mongodb:
   image: mongo:latest
   container_name: "mongodb"
   ports:
    - 27017:27017
 event-store:
   image: eventstore/eventstore
   ports:
     - "2113:2113"
     - "1113:1113"
   extra_hosts:
     - "eventstore.com:127.0.0.1"
     - "localhost:127.0.0.1"
   restart: always
 command-application-1:
   image: zacacj/vitta-challenge-command:1.0-SNAPSHOT
   depends_on:
     - mongodb
     - event-store
     - proxy
   restart: always
 command-application-2:
   image: zacacj/vitta-challenge-command:1.0-SNAPSHOT
   depends_on:
     - mongodb
     - event-store
     - proxy
   restart: always
